// Single source of truth for site identity used by SEO, sitemap, JSON-LD.
//
// One repo → two static builds (artist + bureau), one image, two roots
// served by nginx based on the X-Site-Mode request header. PUBLIC_SITE_HOST
// and PUBLIC_DOMAIN_MODE are baked into each build at compile time so
// canonical URLs, og:url, og:site_name, og:image, sitemap entries, and
// JSON-LD `url` fields are all self-consistent per origin without runtime
// rewriting.
//
// Defaults (when no env var is set) match the bureau identity — that's the
// most-trafficked apex (denfrievilje.dk) and the historical default in
// +layout.svelte's hostname check.

import { PUBLIC_SITE_HOST, PUBLIC_DOMAIN_MODE } from '$env/static/public';

const HOST = PUBLIC_SITE_HOST || 'denfrievilje.dk';
export const SITE_URL = `https://${HOST}`;
export const PRERENDER_BUREAU = PUBLIC_DOMAIN_MODE !== 'artist';

export const SITE_TAGLINE = 'Software Artist & Design Technologist';

export const SITE_NAME_BUREAU = 'Den Frie Vilje';
export const SITE_NAME_ARTIST = 'Ole Kristensen';

export const SITE_DESCRIPTION_ARTIST =
	'Ole Kristensen — visual artist and design technologist. Interactive installations, live performances, and software-driven works based in Copenhagen.';
export const SITE_DESCRIPTION_BUREAU =
	'Den Frie Vilje — design technology consultancy by Ole Kristensen. Interactive installations, live performances, and bespoke software for cultural and commercial clients.';

// 1200×630 OG image fallbacks generated by scripts/generate-og-images.js.
// Filenames are brand slugs (not internal artist/bureau labels) so the
// public asset URL doesn't leak the build-mode terminology.
export const SITE_OG_ARTIST = '/og/default-ole-kristensen.png';
export const SITE_OG_BUREAU = '/og/default-den-frie-vilje.png';

// Person + Organization JSON-LD shared across pages.
export const PERSON_JSONLD = {
	'@context': 'https://schema.org',
	'@type': 'Person',
	name: 'Ole Kristensen',
	url: SITE_URL,
	jobTitle: SITE_TAGLINE,
	address: {
		'@type': 'PostalAddress',
		addressLocality: 'Copenhagen',
		addressCountry: 'DK'
	},
	sameAs: ['https://github.com/olekristensen', 'https://www.linkedin.com/in/olefab']
};

export const ORGANIZATION_JSONLD = {
	'@context': 'https://schema.org',
	'@type': 'Organization',
	name: SITE_NAME_BUREAU,
	legalName: 'Den Frie Vilje ApS',
	url: SITE_URL,
	logo: `${SITE_URL}/logo-black.png`,
	founder: { '@type': 'Person', name: 'Ole Kristensen' },
	address: {
		'@type': 'PostalAddress',
		streetAddress: 'Kronprinsesse Sofies Vej 21, 2th',
		postalCode: '2000',
		addressLocality: 'Frederiksberg',
		addressCountry: 'DK'
	}
};
